### ISSUE TITLE
执行 hrun 时报错

### ISSUE THREAD

**Issue by sionguo** [xuping2012/httprunner_swagger#1]
Traceback (most recent call last):
  File "d:\software\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\software\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\software\Python\Python38-32\Scripts\hrun.exe\__main__.py", line 7, in <module>
  File "d:\software\python\python38-32\lib\site-packages\httprunner\cli.py", line 133, in main_hrun_alias
    main()
  File "d:\software\python\python38-32\lib\site-packages\httprunner\cli.py", line 107, in main
    main_run(extra_args)
  File "d:\software\python\python38-32\lib\site-packages\httprunner\cli.py", line 41, in main_run
    testcase_path_list = main_make(tests_path_list)
  File "d:\software\python\python38-32\lib\site-packages\httprunner\make.py", line 316, in main_make
    __make(tests_path)
  File "d:\software\python\python38-32\lib\site-packages\httprunner\make.py", line 293, in __make
    __make_testcase(test_content)
  File "d:\software\python\python38-32\lib\site-packages\httprunner\make.py", line 177, in __make_testcase
    __make(ref_testcase_path)
  File "d:\software\python\python38-32\lib\site-packages\httprunner\make.py", line 286, in __make
    test_content = ensure_testcase_v3_api(test_content)
  File "d:\software\python\python38-32\lib\site-packages\httprunner\compat.py", line 151, in ensure_testcase_v3_api
    teststep.update(ensure_step_attachment(api_content))
  File "d:\software\python\python38-32\lib\site-packages\httprunner\compat.py", line 139, in ensure_step_attachment
    test_dict["validate"] = convert_validators(step["validate"])
  File "d:\software\python\python38-32\lib\site-packages\httprunner\compat.py", line 80, in convert_validators
    v[comparator][0] = convert_jmespath(v[comparator][0])
IndexError: list index out of range

**Comment by xuping2012** [comment]
httprunner应该是你安装的版本，环境问题导致，报错;IndexError: list index out of range, 看一下你的脚本哪里的参数，导致越界

**Comment by huhaoming** [comment]
C:\Users\Administrator\AppData\Local\Programs\Python\Python39\python.exe C:/Users/Administrator/Desktop/python/httprunner_swagger-master/swaggerLib/Swagger.py
2021-05-26 20:07:25,387-INFO-HandleJson-37-日志信息：Interface Params Total：3 ,write to json file successfully!
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\python\httprunner_swagger-master\swaggerLib\Swagger.py", line 336, in <module>
    js.analysis_json_data(isDuplicated=False)
  File "C:\Users\Administrator\Desktop\python\httprunner_swagger-master\swaggerLib\Swagger.py", line 79, in analysis_json_data
    self.data = res['paths']    # 取接口地址返回的path数据,包括了请求的路径
KeyError: 'paths'

进程已结束，退出代码为 1

**Comment by xuping2012** [comment]
你的swagger接口文档，后面有paths部分吗？
